#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

mb_internal_encoding('UTF-8');
error_reporting(E_ALL & ~(E_NOTICE | E_DEPRECATED | E_STRICT));

defined('YII_DEBUG') or define('YII_DEBUG', false);

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');

Yii::setAlias('@webroot', __DIR__ . '/../');
Yii::setAlias('@web', '/');

$config = require(__DIR__ . '/config/console.php');

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
